// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6NAHQ2O6SIiORDA03yUS9_QhSkdJAdeY',
    appId: '1:26741511759:web:6a37670f2455d7ade03c3a',
    messagingSenderId: '26741511759',
    projectId: 'chat-app-2896b',
    authDomain: 'chat-app-2896b.firebaseapp.com',
    storageBucket: 'chat-app-2896b.appspot.com',
    measurementId: 'G-GPLNFF5L6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOEFFgNWBuwgaUpnvxKgO0iLIIIrZe-o',
    appId: '1:26741511759:android:c5d923abe45f7554e03c3a',
    messagingSenderId: '26741511759',
    projectId: 'chat-app-2896b',
    storageBucket: 'chat-app-2896b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkClbLLo1Yp5z-IgmEqrtIgPHmelgLNE',
    appId: '1:26741511759:ios:717ed5bd98b28759e03c3a',
    messagingSenderId: '26741511759',
    projectId: 'chat-app-2896b',
    storageBucket: 'chat-app-2896b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkClbLLo1Yp5z-IgmEqrtIgPHmelgLNE',
    appId: '1:26741511759:ios:717ed5bd98b28759e03c3a',
    messagingSenderId: '26741511759',
    projectId: 'chat-app-2896b',
    storageBucket: 'chat-app-2896b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6NAHQ2O6SIiORDA03yUS9_QhSkdJAdeY',
    appId: '1:26741511759:web:5dd9a6740c107157e03c3a',
    messagingSenderId: '26741511759',
    projectId: 'chat-app-2896b',
    authDomain: 'chat-app-2896b.firebaseapp.com',
    storageBucket: 'chat-app-2896b.appspot.com',
    measurementId: 'G-3H1P10P5VV',
  );
}
